// Generated by Website Factory. Update via the factory pipeline, not by hand.

export interface MenuItem {
  name: string;
  native?: string;
  nr?: string;
  description?: string;
  price: string;
  spicy?: boolean;
  vegan?: boolean;
  note?: string;
}

export type MenuCategory = {
  id: string;
  label: string;
  native?: string;
  intro?: string;
  items: MenuItem[];
};

export const menuDataGeneratedFromFactory = true;

export const menuImageUrls: string[] = [];

export const menuCategories: MenuCategory[] = [
  {
    "id": "vorspeisen",
    "label": "Vorspeisen",
    "items": [
      {
        "name": "Carpaccio di Manzo",
        "description": "mit Parmesan und Rucola",
        "price": "14,00 €"
      },
      {
        "name": "Schafskäse überbacken",
        "price": "10,50 €"
      },
      {
        "name": "Bruschetta",
        "price": "6,50 €"
      }
    ]
  },
  {
    "id": "insalate",
    "label": "Insalate",
    "intro": "Frische, knackige Salate mit Dressings Ihrer Wahl: Hausdressing, Joghurtdressing oder Balsamicodressing",
    "items": [
      {
        "name": "Grüner Salat",
        "description": "mit Tomaten, Gurken und Oliven",
        "price": "5,00 €"
      },
      {
        "name": "Italienischer Salat",
        "description": "mit Tomaten, Gurken, Käse, Schinken, Ei, Oliven und Peperoni. Wahl aus: Klein oder Groß",
        "price": "6,50 €"
      },
      {
        "name": "Contadina Salat",
        "description": "mit Tomaten, Gurken, Käse, Schinken, Ei, Oliven, Peperoni, Thunfisch und Zwiebeln. Wahl aus: Klein oder Groß",
        "price": "7,50 €"
      },
      {
        "name": "Bauernsalat",
        "description": "mit Schafskäse, Paprika, Zwiebeln, Gurken, Tomaten, Sellerie und Schafskäse",
        "price": "11,00 €"
      },
      {
        "name": "Insalata Caprese",
        "description": "mit Tomaten, Büffelmozzarella und Oliven",
        "price": "12,50 €"
      },
      {
        "name": "Nizzasalat",
        "description": "mit Tomaten, Gurken, Käse, Oliven, Peperoni, Thunfisch, Krabben und Artischocken",
        "price": "11,00 €"
      },
      {
        "name": "Insalata di Pollo",
        "description": "mit Hähnchenbrustfilet, Tomaten, Gurken, Mais und Paprika",
        "price": "11,00 €"
      },
      {
        "name": "Insalata Toscana",
        "description": "mit Rucola, Cherrytomaten, gehobelter Parmesan, Mozzarella, Frischkäse und Balsamicocreme",
        "price": "11,00 €"
      }
    ]
  }
];
