// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type WeekdayHours = {
  day: string;
  time: string;
  closed: boolean;
};

export type RestaurantConfig = {
  name: string;
  shortName: string;
  tagline: string;
  logoGlyph: string;
  cuisine: string;
  website?: string;
  priceRange?: string;
  coordinates?: {
    latitude: number;
    longitude: number;
  };
  nativeTagline: string;
  nativeTaglineTranslation: string;
  phone: string;
  phoneLink: string;
  landlinePhone?: string;
  landlinePhoneLink?: string;
  email: string;
  address: {
    street: string;
    cityLine: string;
    city: string;
  };
  mapsUrl: string;
  googleBusinessProfileUrl: string;
  socialMedia: {
    instagram: string;
    facebook: string;
    tiktok: string;
    hidden: {
      instagram: boolean;
      facebook: boolean;
      tiktok: boolean;
    };
    titleHidden: boolean;
  };
  closedDays: number[];
  closedDaysLabel: string;
  hours: WeekdayHours[];
  reservationTimeSlots: {
    startHour: number;
    endHour: number;
    stepMinutes: number;
    latestMinutes: number;
  };
  seo: {
    title: string;
    description: string;
    keywords: string[];
    ogTitle: string;
    ogDescription: string;
    locale: string;
  };
  legal: {
    ownerName: string;
    vatId: string;
    responsiblePerson: string;
  };
};

export const restaurant: RestaurantConfig = {
  "name": "Casa della Pizza",
  "shortName": "Casa della Pizza",
  "tagline": "Italienisch",
  "logoGlyph": "C",
  "cuisine": "Italienisch",
  "nativeTagline": "",
  "nativeTaglineTranslation": "",
  "phone": "06202 5827553",
  "phoneLink": "tel:+4962025827553",
  "email": "",
  "address": {
    "street": "Mannheimer Straße 14 B",
    "cityLine": "68723 Oftersheim",
    "city": "Oftersheim"
  },
  "mapsUrl": "https://maps.google.com/?cid=13365070258729384808&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
  "googleBusinessProfileUrl": "https://maps.google.com/?cid=13365070258729384808&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
  "socialMedia": {
    "instagram": "https://www.instagram.com/la_casa_della_pizza/",
    "facebook": "https://www.facebook.com/100092478738159/",
    "tiktok": "https://www.tiktok.com/@lacasadellapizza_pan",
    "hidden": {
      "instagram": false,
      "facebook": false,
      "tiktok": false
    },
    "titleHidden": false
  },
  "closedDays": [
    1
  ],
  "closedDaysLabel": "Geschlossen: Montag.",
  "hours": [
    {
      "day": "Montag",
      "time": "Geschlossen",
      "closed": true
    },
    {
      "day": "Dienstag, Mittwoch & Donnerstag",
      "time": "11:00–14:00 Uhr, 17:00–22:00 Uhr",
      "closed": false
    },
    {
      "day": "Freitag",
      "time": "11:00–14:00 Uhr, 17:00–23:00 Uhr",
      "closed": false
    },
    {
      "day": "Samstag",
      "time": "17:00–23:00 Uhr",
      "closed": false
    },
    {
      "day": "Sonntag",
      "time": "11:30–21:30 Uhr",
      "closed": false
    }
  ],
  "reservationTimeSlots": {
    "startHour": 17,
    "endHour": 21,
    "stepMinutes": 30,
    "latestMinutes": 30
  },
  "seo": {
    "title": "Casa della Pizza | Italienisch in Oftersheim",
    "description": "Casa della Pizza in Oftersheim. italienische Küche, aktuelle Öffnungszeiten und Kontaktinformationen auf einen Blick.",
    "keywords": [
      "Casa della Pizza",
      "Italienisch Oftersheim",
      "Casa della Pizza Oftersheim"
    ],
    "ogTitle": "Casa della Pizza",
    "ogDescription": "Casa della Pizza in Oftersheim. italienische Küche, aktuelle Öffnungszeiten und Kontaktinformationen auf einen Blick.",
    "locale": "de_DE"
  },
  "legal": {
    "ownerName": "",
    "vatId": "",
    "responsiblePerson": ""
  }
};

export function isClosedDay(dateStr: string): boolean {
  if (!dateStr) return false;
  const day = new Date(dateStr).getDay();
  return restaurant.closedDays.includes(day);
}

export function generateTimeSlots(): string[] {
  const startHour: number = restaurant.reservationTimeSlots.startHour;
  const endHour: number = restaurant.reservationTimeSlots.endHour;
  const stepMinutes: number = restaurant.reservationTimeSlots.stepMinutes;
  const latestMinutes: number = restaurant.reservationTimeSlots.latestMinutes;
  const slots: string[] = [];
  for (let hour = startHour; hour <= endHour; hour++) {
    for (let minute = 0; minute < 60; minute += stepMinutes) {
      if (hour === endHour && minute > latestMinutes) break;
      const hh = hour.toString().padStart(2, "0");
      const mm = minute.toString().padStart(2, "0");
      slots.push(`${hh}:${mm}`);
    }
  }
  return slots;
}
