// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 4.5,
  "totalRatings": 146,
  "reviews": [
    {
      "author": "Aylien Feger",
      "rating": 5,
      "text": "Tutto bene e delizioso\nSehr lecker – man sollte vorher angeben, ob die Pizza geschnitten wird.\nSo eine Pizza findet man in Deutschland selten.\nGanz klar Geschmack wie in Bella Italia 💚🤍❤️",
      "time": "vor 4 Monaten"
    },
    {
      "author": "Gottfried Witiko Friedrich Melle-Wladika",
      "rating": 5,
      "text": "Haben hier für meinen Geburtstag Partypizzen bestellt. Lieferung war pünktlich, Pizzen haben sehr gut geschmeckt, und kulanterweise wurde eine fehlerhaft belegte Pizza sogar kostenfrei ausgetauscht. Super Service!",
      "time": "vor 7 Monaten"
    },
    {
      "author": "M S",
      "rating": 5,
      "text": "Die Pizzeria hat am 29.04.23 neu eröffnet.\nGestern war ich das erste Mal dort und habe zwei Pizzen bestellt.\n\nMan kann dem Pizzabäcker bei der Zubereitung zuschauen, was ich persönlich sehr wichtig finde.\nIch hatte Sonderwünsche für meine Pizza was den Belag und die Zubereitung betraf.\nBeides war überhaupt kein Problem und wurde freundlich umgesetzt.\nIch hatte nach den Zutaten gefragt und auch hier konnte mir der Pizzabäcker Auskunft geben.\n\nInfo für Pizza-Enthusiasten:\nFür den Teig wird Caputo Mehl verwendet und Fior di Latte Mozzarella, der Teig ruht 72 Stunden.\nDie Qualität der Zutaten und die lange Teigruhe schmeckt man.\n\nFreundlicherweise gab es noch einen Gruß aus der Küche gratis dazu, ein mit Nutella gefüllter Pizzateig, welcher auch sehr lecker war.\n\nEs gibt übrigens eine Treuekarte.\n\nFazit:\nGerne wieder 👍",
      "time": "vor 3 Jahren"
    }
  ]
};
